;; GENERATED by bin/render.cljs — do not edit by hand.
;; Regenerate: nbb --classpath render:../terrain/src bin/render.cljs
(ns byoubu.poster
  "Manifest of the tier-1 poster artifacts in resources/.

  Generated, so it cannot drift from the files: the digests below were
  computed from the exact bytes written in the same run that wrote this
  namespace. `src/` can therefore state what a poster is without doing
  file IO (which differs between CLJ and CLJS) and without depending on
  a hash implementation."
  (:require [kotoba.lang.text :as str]))

(def dimensions {:width 1600 :height 900})

(def generated-by
  "Repo pins of what produced these artifacts. Unlike
  byoubu.catalog/generator's nil pin before any render existed, these
  are the shas that actually ran."
  {:terrain "73b8ae27af8b376dc9b5ef73b68f631e35ca2b74", :byoubu "519e3f73a6ab043f69f41869eafffddc302454ae"})

(def posters
  "id -> {:path :bytes :sha256}. :path is relative to the classpath
  resource root, i.e. resources/<path>."
  {   :cobalt-dune
   {:path "byoubu/posters/cobalt-dune.svg"
    :bytes 19207
    :sha256 "572ead7b21d113004cca2a703e1b064945599ac63136ddda3d167b990c55514d"}

   :ember-mesa
   {:path "byoubu/posters/ember-mesa.svg"
    :bytes 19075
    :sha256 "b247bd8a9efc50575381006eca2c39f63d57ded5d9c456dbb3368f19cabf883c"}

   :purple-desert
   {:path "byoubu/posters/purple-desert.svg"
    :bytes 25276
    :sha256 "632b104c90143574be4f299c48839b83e6878af5f57984e904da27ba06aa7638"}

   :salt-flat
   {:path "byoubu/posters/salt-flat.svg"
    :bytes 9544
    :sha256 "aeb3f1bbb4dd11864cc4576bc9194fd8cef60e938b5e1999723d15f797ac0042"}})

(defn poster
  "Manifest entry for a backdrop id, or nil."
  [id]
  (get posters id))

(defn url
  "Poster URL under a base path, e.g. (url :purple-desert \"/assets\")
  => \"/assets/byoubu/posters/purple-desert.svg\". Returns nil for an
  id with no rendered poster."
  [id base]
  (when-let [p (:path (poster id))]
    (str (str/replace (or base "") #"/$" "") "/" p)))
